apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: democonfig-service
spec:
  selector:
    app: pacman-api-config
  ports:
    - protocol: "TCP"
      NordPort: 30236
      port: 80 # The port that the service is running on in the cluster
      targetPort: 8888 # The port exposed by the service
  type: NordPort # type of the service. LoadBalancer indicates that our service will be external.
---
apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: pacman-api-config
spec:
  selector:
    matchLabels:
      app: pacman-api-config
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: pacman-api-config
    spec:
      containers:
        - name: pacman-api-config
          image: configapi:first # Image that will be used to containers in the cluster
          imagePullPolicy: Never
          ports:
            - containerPort: 8888
---
apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: authdemo-service
spec:
  selector:
    app: pacman-api-auth
  ports:
    - protocol: "TCP"
      NordPort: 31621
      port: 80 # The port that the service is running on in the cluster
      targetPort: 8087 # The port exposed by the service
  type: NordPort # type of the service. LoadBalancer indicates that our service will be external.
---
apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: authdemo-deployment
spec:
  selector:
    matchLabels:
      app: pacman-api-auth
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: pacman-api-auth
    spec:
      containers:
        - name: pacman-api-auth
          image: authapi:first # Image that will be used to containers in the cluster
          imagePullPolicy: Never
          ports:
            - containerPort: 8087 
---
apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: admindemo-service
spec:
  selector:
    app: pacman-api-admin
  ports:
    - protocol: "TCP"
      port: 80 # The port that the service is running on in the cluster
      targetPort: 8084 # The port exposed by the service
  type: NodePort # type of the service. LoadBalancer indicates that our service will be external.
---
apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: admindemo-deployment
spec:
  selector:
    matchLabels:
      app: pacman-api-admin
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: pacman-api-admin
    spec:
      containers:
        - name: pacman-api-admin
          image: adminapi:v1 # Image that will be used to containers in the cluster
          imagePullPolicy: Never
          ports:
            - containerPort: 8084
---
apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: assetdemo-service
spec:
  selector:
    app: pacman-api-asset
  ports:
    - protocol: "TCP"
      port: 80 # The port that the service is running on in the cluster
      targetPort: 8083 # The port exposed by the service
  type: NodePort # type of the service. LoadBalancer indicates that our service will be external.
---
apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: assetdemo-deployment
spec:
  selector:
    matchLabels:
      app: pacman-api-asset
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: pacman-api-asset
    spec:
      containers:
        - name: pacman-api-asset
          image: assetapi:v1 # Image that will be used to containers in the cluster
          imagePullPolicy: Never
          ports:
            - containerPort: 8083
          
